title: di0n1xd blog
description: "En esta web colgare todo lo que haga relacionado con ciberseguridad."
author:
  name: "Denís López Alarcón"
  email: "di0n1xd.oficial@gmail.com"
  url: "https://github.com/di0n1xd/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "di0n1xd"
year : "2023"
